# -*- coding: utf-8 -*-
"""03장 연습문제.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1aXofLBAb9WfYh-wD0Uf88BV8LxTTRI1W
"""

result = 0 
i = 1
while i <= 1000:
     if i % 3 == 0:
       result += i
     i += 1
print(result)

i = 0
while i<5:
  i = i + 1
  print("*"*i)

i = 0
while True:
  i += 1
  if i > 5: break
  print('*' * i)

i = 1
for i in range(1, 101):
  print(i)

classA = [70,60,55,75,95,90,80,80,85,100]
add = 0
for i in classA:
  add = add + i
  average = add / len(classA) 
print(average)

A = [70, 60, 55, 75, 95, 90, 80, 80, 85, 100]
total = 0

for score in A:
  total += score

average = total / len(A)
print(average)

numbers = [1,2,3,4,5]
result = [n*2 for n in numbers if n%2 == 1]
print(result)

